theme: minima
title: Coding Through The Eyes of Nat 
author: Nathaly
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
With the "Coding Through The Eyes of Nat" blog I plan to take you through my journey into the coding world!

# social links
twitter_username: Nathaly42216704 # DO NOT include the @ character, or else the build will fail!
github_username:  nath248 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
